"""initial migration

Revision ID: 545eabe1b69d
Revises: 
Create Date: 2024-05-01 14:33:29.510525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '545eabe1b69d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('댓글')
    op.drop_table('학습 진도 현황')
    op.drop_table('학생')
    op.drop_table('시간표')
    op.drop_table('선생')
    op.drop_table('과제')
    op.drop_table('대시보드')
    op.drop_table('챗봇')
    op.drop_table('메모장')
    op.drop_table('문제')
    op.drop_table('게시판')
    op.drop_table('첨부파일')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('첨부파일',
    sa.Column('파일ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('게시물ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('파일명', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('파일경로', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('시간', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['게시물ID'], ['게시판.게시물ID'], name='첨부파일_ibfk_1'),
    sa.PrimaryKeyConstraint('파일ID'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('게시판',
    sa.Column('게시물ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('대시보드key', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('제목', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('학생ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('선생ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('작성내용', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('작성시간', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['대시보드key'], ['대시보드.대시보드key'], name='게시판_ibfk_1'),
    sa.ForeignKeyConstraint(['선생ID'], ['선생.선생ID'], name='게시판_ibfk_3'),
    sa.ForeignKeyConstraint(['학생ID'], ['학생.학생ID'], name='게시판_ibfk_2'),
    sa.PrimaryKeyConstraint('게시물ID'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('문제',
    sa.Column('문제번호', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('대시보드', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('유형', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('문제질문', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('문제내용', mysql.TEXT(), nullable=True),
    sa.Column('보기1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('보기2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('보기3', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('보기4', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('보기5', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('정답', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('문항UID', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('빈칸개수', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('빈칸1의정답', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('빈칸2의정답', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('빈칸3의정답', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('빈칸4의정답', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('빈칸5의정답', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['대시보드'], ['대시보드.대시보드key'], name='문제_ibfk_1'),
    sa.PrimaryKeyConstraint('문제번호'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('메모장',
    sa.Column('작성자id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('내용', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('작성자id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('챗봇',
    sa.Column('시간', mysql.DATETIME(), nullable=False),
    sa.Column('학생ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('질문', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('챗봇응답', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['학생ID'], ['학생.학생ID'], name='챗봇_ibfk_1'),
    sa.PrimaryKeyConstraint('시간', '학생ID'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('대시보드',
    sa.Column('대시보드key', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('과목명', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('학년', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('학급', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('담당선생ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['담당선생ID'], ['선생.선생ID'], name='대시보드_ibfk_1'),
    sa.PrimaryKeyConstraint('대시보드key'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('과제',
    sa.Column('과제ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('학생id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('과목_번호', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('과제_제목', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('과제_내용', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['과목_번호'], ['대시보드.대시보드key'], name='과제_ibfk_2'),
    sa.ForeignKeyConstraint(['학생id'], ['학생.학생ID'], name='과제_ibfk_1'),
    sa.PrimaryKeyConstraint('과제ID'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('선생',
    sa.Column('선생ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('성별', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('이름', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('생년월일', sa.DATE(), nullable=True),
    sa.Column('이메일', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('선생ID'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('시간표',
    sa.Column('대시보드key', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('요일', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('시간', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('대시보드key', '요일', '시간'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('학생',
    sa.Column('학생ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('성별', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('이름', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('생년월일', sa.DATE(), nullable=True),
    sa.Column('휴대폰번호', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('학년', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('학급', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('학생ID'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('학습 진도 현황',
    sa.Column('학생id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('내용', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('학생id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('댓글',
    sa.Column('댓글ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('작성자ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('내용', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('댓글시간', mysql.DATETIME(), nullable=True),
    sa.Column('게시물ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['게시물ID'], ['게시판.게시물ID'], name='댓글_ibfk_1'),
    sa.PrimaryKeyConstraint('댓글ID'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
